# Generated by Django 4.1.6 on 2023-02-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("no_emission", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emission", old_name="datetime", new_name="time_date",
        ),
    ]
