name: Django CI

on: push

jobs:
  test_project:
    runs-on: windows-latest #os of python.anywhere

    steps:
    - uses: actions/checkout@v2  #checks out the repository, stays available for others
    - name: Set up Python 
      uses: actions/setup-python@v2 #installs demanded python version 
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python gasag_interview/gasag_interview/manage.py test
